services:
  clockapi:
    image: clockapi
    build:
      context: .
      dockerfile: ClockAPI/Dockerfile
    ports:
      - "5010:80"
      - "5011:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORTS=5011
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ReplaceWithYourCertPass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ClockInOut.pfx
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=clockinoutdb;Username=postgres;Password=mysecretpassword
    volumes:
      - ${HOME}/.aspnet/https:/https/
      - ${HOME}/.aspnet/DataProtection-Keys:/home/app/.aspnet/DataProtection-Keys
    depends_on:
      - postgres

  userapi:
    image: userapi
    build:
      context: .
      dockerfile: UserAPI/Dockerfile
    ports:
      - "5020:80"
      - "5021:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORTS=5021
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ReplaceWithYourCertPass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ClockInOut.pfx
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=clockinoutdb;Username=postgres;Password=mysecretpassword
    volumes:
      - ${HOME}/.aspnet/https:/https/
      - ${HOME}/.aspnet/DataProtection-Keys:/home/app/.aspnet/DataProtection-Keys
    depends_on:
      - postgres

  teamapi:
    image: teamapi
    build:
      context: .
      dockerfile: TeamAPI/Dockerfile
    ports:
      - "5030:80"
      - "5031:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORTS=5031
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ReplaceWithYourCertPass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ClockInOut.pfx
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=clockinoutdb;Username=postgres;Password=mysecretpassword
    volumes:
      - ${HOME}/.aspnet/https:/https/
      - ${HOME}/.aspnet/DataProtection-Keys:/home/app/.aspnet/DataProtection-Keys
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: clockinoutdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: